### PR TITLE
Snr

### PR DESCRIPTION
**Pull request by buzinsky**
Pull request for merging SNR changes into develop. Please do not merge until we agree and other issues are resolved. (will add with github interface)

### CODE REVIEW

**Comment by buzinsky** [comment]
https://github.com/Helium6CRES/he6-cres-spec-sims/blob/48322ded91fa5adc68087920100e91f6d2bfc1ec/he6_cres_spec_sims/simulation_blocks.py#L627

I can't get this in the same format as other issues. When scattering is working, this line throws an error
Part of the challenge is that doing print(type(energy_stop)) gives 
<class 'numpy.float64'> , then
<class 'pandas.core.series.Series'> after.

**EDIT: Resolved. See https://github.com/Helium6CRES/he6-cres-spec-sims/pull/4/commits/c47fb1cc05b8d3283cb434d91f0b9982e4585b99**

**Comment by buzinsky** [comment]
I kind of messed up this pull request, really you should have made it
Scattering was broken, due to the energy_stop bug fix you put in. I believe I fixed that. The parameters you use in your configs do not allow for any scatters to happen (see above)

I do get spectrograms. It is not perfect (appear in dead region, noise files should not be duplicated for _0 and _1), but this is a starting point. I think this is now functional enough for us to merge to develop. You can tackle (or defer) the above points before or after merging this

Screenshot 2024-05-14 at 5 09 31 PM
Screenshot 2024-05-14 at 5 16 02 PM

**Comment by rjtayl** [comment]
While reviewing this I found an issue where scattered track segments were not being given a file acquisition number, and therefore not being included in the spec files. Fixed with https://github.com/Helium6CRES/he6-cres-spec-sims/pull/4/commits/66372d19f50e6951a18620d6fe6fd4daaf850cec. Now my sparse specs are showing reasonable scattering:
image

**Review by rjtayl — APPROVED** [review]
With scattering seemingly working now I think we are good to merge this. I am deferring the other issues with SNR to be fixed after the merge. Merging this now will let us work on our general restructuring and cleaning up we wanted to do before building new features (including a better implementation of SNR)

**Pull request merged**
